# Generated by Django 2.0.6 on 2018-06-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(null=True, upload_to='yamda/static/yamda/img/'),
        ),
    ]
