# Generated by Django 2.0.6 on 2018-06-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180607_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
